#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

killall picom
picom &

killall feh
feh --bg-fill ~/Pictures/wallpapers/38580.jpg &

killall udiskie
udiskie &

killall polybar
$HOME/.config/polybar/launch.sh &

# - - - Monitor - - -
bspc monitor HDMI-0 -d I II III IV V
bspc monitor DP-0 -d VI VII VIII IX X

#### BSPWM Config ####
#bspc config border_width       8
bspc config border_width         2
bspc config window_gap          12
#bspc config top_padding         20
#bspc config bottom_padding     0
#bspc config left_padding       0
#bspc config right_padding      0
#bspc config single_monocle     false
#bspc config click_to_focus     true
#bspc config split_ratio        0.50
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config focus_by_distance          true
# bspc config focus_follows_pointer       true
#bspc config remove_disabled_montors    true
#bspc config merge_overlapping_monitors true
#bspc config pointer_modifier           mod4
#bspc config pointer_action1            move
#bspc config pointer_action2            resize_side
#bspc config pointer_action3            resize_corner


#### BSPWM Coloring ####
bspc config normal_border_color        "#928374" # "#4c566a"
bspc config active_border_color        "#282828" # "#1e1e1e"
bspc config focused_border_color       "#d65d0e" # "#c1f2b0" # #ff9999
bspc config presel_feedback_color      "#d65d0e" # "#b5e719" # #ff9999
bspc config urgent_border_color        "#cc241d" # "#dd2727"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^6' follow=on
bspc rule -a vlc state=floating
# bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# desktop='^6' 		-> application will appear on the desktop 6 
# state=floating	-> the application will open in a floating window
# follow=on			-> opening an app, we will automatically switch to the desktop where it should be opened
# focus=on			-> when an application is opened, esa ventana estará enfocada
# manage=off		-> the application will open in a strange way,
						# will not open in one window,
						# will visually overlap other windows,
						# but wont be focused
